# Generated by Django 6.0.2 on 2026-03-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0002_property_free_vehicle_facility_property_offers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_lift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_power_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times viewed'),
        ),
    ]
