# Generated by Django 6.0.2 on 2026-03-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='Link to 360 Virtual Tour or Video', max_length=500, null=True),
        ),
    ]
