# Generated by Django 6.0.2 on 2026-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0007_lease_paymentsplit_taxreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='facing',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north-east', 'North-East'), ('north-west', 'North-West'), ('south-east', 'South-East'), ('south-west', 'South-West')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(default=0, help_text='Floor number (0 for ground)'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished_status',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi-furnished', 'Semi-Furnished'), ('fully-furnished', 'Fully-furnished')], default='unfurnished', max_length=20),
        ),
    ]
