# Generated by Django 6.0.2 on 2026-03-11 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0009_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties_app.property'),
        ),
    ]
