# Generated by Django 6.0.3 on 2026-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_app', '0010_alter_inquiry_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_plan',
            field=models.ImageField(blank=True, help_text='Property Floor Plan', null=True, upload_to='floor_plans/'),
        ),
    ]
